# Slightly adapted from docker4drupal.
# See https://docker4drupal.readthedocs.io/en/latest/
version: "2"

services:
  # The database container.
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    # Pass environment variables to the container.
    environment:
      # See all available mariadb variables at https://github.com/wodby/mariadb.
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    # Persistent data for this container.
    volumes:
      # See README.md in /docker/mariadb-init.
      - ./mariadb-init:/docker-entrypoint-initdb.d  

  # The php container.
  php:
# 2. Images without Drupal â€“ wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-php:7.1-2.4.2
#    image: wodby/drupal-php:7.0-2.4.2
#    image: wodby/drupal-php:5.6-2.4.2
#    image: wodby/drupal-php:5.3-2.4.2
    # Pass environment variables to the container.
    environment:
      # See all available PHP variables at https://github.com/wodby/php.
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_TIMEZONE: America/New_York
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    # Persistent data for this container.
    volumes:
#      - codebase:/var/www/html
# Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos/)
      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
      - ~/.ssh:/root/.ssh

  # The web container.
  nginx:
# wodby/drupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-nginx:8-1.13-2.4.0
#    image: wodby/drupal-nginx:7-1.13-2.4.0
#    image: wodby/drupal-nginx:6-1.13-2.4.0
#    image: wodby/drupal-nginx:8-1.12-2.4.0
#    image: wodby/drupal-nginx:7-1.12-2.4.0
#    image: wodby/drupal-nginx:6-1.12-2.4.0
    depends_on:
      - php
    # Pass environment variables to the container.
    environment:
      # See all available NGINX variables at https://github.com/wodby/php.
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    # Persistent data for this container, map host to container locations.
    volumes:
#      - codebase:/var/www/html
# Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos/)
      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
    labels:
      - "traefik.backend=nginx"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.docker.localhost"

#  apache:
#    image: wodby/drupal-apache:2.4-1.0.0
#    depends_on:
#      - php
#    environment:
#      APACHE_LOG_LEVEL: debug
#      APACHE_BACKEND_HOST: php
#      APACHE_SERVER_ROOT: /var/www/html/web
#    volumes:
#      - codebase:/var/www/html
## Options for macOS users (http://docs.docker4drupal.org/en/latest/macos)
##      - codebase:/var/www/html:cached # User-guided caching
##      - docker-sync:/var/www/html # Docker-sync
#    labels:
#      - 'traefik.backend=apache'
#      - 'traefik.port=80'
#      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.docker.localhost"

#  varnish:
#    image: wodby/drupal-varnish:4.1-2.1.2
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - "traefik.frontend.rule=Host:varnish.${COMPOSE_PROJECT_NAME}.docker.localhost"

#  redis:
#    image: wodby/redis:3.2-2.1.1

#  adminer:
#    image: wodby/adminer:4.3-1.1.0
#    environment:
#      ADMINER_SALT: adminer-salt
#    labels:
#      - 'traefik.backend=adminer'
#      - 'traefik.port=9000'
#      - "traefik.frontend.rule=Host:adminer.${COMPOSE_PROJECT_NAME}.docker.localhost"

#  pma:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mariadb
#      PMA_USER: drupal
#      PMA_PASSWORD: drupal
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    labels:
#      - 'traefik.backend=pma'
#      - 'traefik.port=80'
#      - "traefik.frontend.rule=Host:pma.${COMPOSE_PROJECT_NAME}.docker.localhost"

#  solr:
## wodby/drupal-solr:[DRUPAL_VERSION]-[SOLR_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal-solr:8-6.4-2.1.0
##    image: wodby/drupal-solr:8-6.3-2.1.0
##    image: wodby/drupal-solr:8-5.5-2.1.0
##    image: wodby/drupal-solr:7-5.4-2.1.0
#    environment:
#      SOLR_HEAP: 1024m
#    labels:
#      - 'traefik.backend=solr'
#      - 'traefik.port=8983'
#      - "traefik.frontend.rule=Host:solr.${COMPOSE_PROJECT_NAME}.docker.localhost"

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - "traefik.frontend.rule=Host:mailhog.${COMPOSE_PROJECT_NAME}.docker.localhost"

#  nodejs:
#    image: wodby/drupal-node:1.0-1.0.0
#    environment:
#       NODE_SERVICE_KEY: node-service-key
#    labels:
#      - 'traefik.backend=nodejs'
#      - 'traefik.port=8080'
#      - "traefik.frontend.rule=Host:nodejs.${COMPOSE_PROJECT_NAME}.docker.localhost"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  node:
#    image: node:alpine
#    working_dir: /app
#    labels:
#      - 'traefik.backend=node'
#      - 'traefik.port=3000'
#      - "traefik.frontend.rule=Host:front.${COMPOSE_PROJECT_NAME}.docker.localhost"
#    expose:
#      - "3000"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  memcached:
#    image: wodby/memcached:1.4-2.0.0

#  rsyslog:
#    image: wodby/rsyslog

#  athenapdf:
#    image: arachnysdocker/athenapdf-service
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: false

  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - "traefik.frontend.rule=Host:portainer.${COMPOSE_PROJECT_NAME}.docker.localhost"

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# The volume where data needs to be persisted and shared with the host.
volumes:
  codebase:
## Docker-sync for macOS users
#  docker-sync:
#    external: true
